keys:
  - &root age1a890chv8t8nqzxw6vzusmtwc4mqhqtsevx4xpgj0ez7jr0a8napq937kys
  - &fawaz age1zpc6ej5qaa8nxre64ud0xsgxkhj0gqre7md4ykwty34qnpe9qfgq6cl5d8
creation_rules:
  - path_regex: system/secrets.yaml
    key_groups:
      - age:
        - *root
  - path_regex: home/secrets.yaml
    key_groups:
      - age:
        - *fawaz
